[package]
name = "cli_typing_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clearscreen = "3.0.0"
edit-distance = "2.1.0"
rand = "0.8.5"
